name: CI
on:
  push: { branches: ["**"] }
  pull_request: { branches: ["**"] }

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: { php: ['8.2','8.3'] }
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          tools: composer:v2
          extensions: mbstring, intl
      - uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache
            vendor
          key: composer-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-${{ matrix.php }}-
      - run: composer install --no-interaction --prefer-dist
      - run: mkdir -p build/coverage-html && vendor/bin/phpunit --coverage-text
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.php }}
          path: build/coverage-html

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: { php-version: '8.3', tools: composer:v2 }
      - uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache
            vendor
          key: composer-phpstan-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-phpstan-
      - run: composer install --no-interaction --prefer-dist
      - run: vendor/bin/phpstan analyse --no-progress

  cs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: { php-version: '8.3', tools: composer:v2 }
      - uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache
            vendor
          key: composer-cs-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-cs-
      - run: composer install --no-interaction --prefer-dist
      - run: vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --diff
